# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

abstract_target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'Lamstagram' do
    pod 'Swinject'
  end

  target 'LamstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LamstagramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
